const chapter = Vue.extend({
  template: `
    <div class="content-image"><img style="margin-bottom:1em;" src="images/trackback-cover.jpg" width="100%" />
      <p style="margin-top=-0.5em;" class="side"><a href="http://gum.co/SPYX" class="gumroad-button">buy it</a>
        <script type="text/javascript" src="https://gumroad.com/js/gumroad.js"></script>
      </p>
    </div>
    <div class="content">
      <h3>Track 01 - Snapshot</h3>
      <p>Life's stories are like tracks on an album of music. Some are short, others are long; most are only vaguely related, but are most definitely related; many things make them unique, but I guarantee that someone you'll never meet is still out there somewhere singing a similar song.</p>
      <p>The snow had just stopped falling when the man wiped the fog off one of his apartment's windows and looked outside at the parking lot below. It was calm and peaceful – nobody was outside, the area was silent, and the snow, mostly unbroken, covered everything in a thin, white, pure coat – but right now he was too worried about the roads to appreciate it. He didn't know how icy they would be, and in a scant hour or so the sun would drop, making it that much harder to see whoever was going to crash into him as he drove to pick up his date.</p>
      <p>He frowned and reached up and closed the blinds and made his way through the apartment over to his bathroom, pausing by his stereo to hit Play. A soft rock song blared out, one he had heard many times. He hummed along as the shower heated up, and as he soaked in the hot water, it and the soap suds splashing across his body, he hummed the only lyric he could remember.</p>
      <p><em>Every picture tells a story...</em></p>
      <p>He had started the process all over again, getting the girl to go out with him, cleaning himself up, taking her to a nice place for a good meal, and then...who knows? All he could say for certain was that he really, really, really wanted to make a good impression this time.</p>
      <p>He turned off the shower and got out and dried himself off. He stood in front of the mirror and sighed, brushing his hair a thousand different ways, but it all came out looking the same. Oh well, he told himself, if it turns out too bad then make the best out of it and just laugh it off.</p>
      <p>He got dressed in his finest clean clothes and threw on his jacket and gloves and cap, then locked up his apartment and walked down the steps and outside and over to his car, the snow crunching beneath his feet. It was still peaceful, and he was all alone. He looked at the crisp, unbroken layer of snow that led out the parking lot and into the street. There had to be a good inch or two of ice underneath, he figured. Damn it.</p>
      <p>He scraped the ice off his windshield and got into his car and shoved the key into the ignition, but the car wouldn't start. Of course. He tried the ignition a few more times. Nothing. He closed his eyes and sighed, then smashed his forehead into the steering wheel. His car horn blared weakly.</p>
      <p style="center">+++</p>
      <p>The woman slipped into a blue dress she found in her closet. It looked nice enough, she figured. Then she figured it might not. She fussed in front of the mirror until she realized he would show up in a few minutes – not enough time to find a new dress. It'll look fine, she told herself. It'll look fine. She slapped on some makeup and tussled her hair and pursed her lips and angled her head away from the mirror, enough to catch the angle of her face with the shape of her hair.</p>
      <p>Yeah, she looked pretty enough. The important thing, she figured, was to tell herself she was pretty as often as possible. It was true, after all. She was pretty enough.</p>
      <p>She stood by the window of her house, which she was renting with her ex-boyfriend. Her ex had showed up late to the first date. Why did she ever decide to move in with him? He kept a photo of the two of them up on a ledge. He was an ass. One time he came home, drunk, flinging himself at her. "I think you owe me something, my dear," he slurred and bellowed.</p>
      <p><em>She</em> owed <em>him</em>? She picked up the photo, remembered a very brief time when she actually liked him, and then considered smashing the frame to bits ... but decided against it. He would throw a huge fit and rampage through the house, yelling and pounding on the walls, and it wasn't worth the hassle of calling the police again. She needed a roommate too badly.</p>
      <p>Outside, the sun was just dialing back over the horizon, the last few rays shooting up and over and illuminating the small town. In a few minutes they were gone and there was only darkness.</p>
      <p>Right as she was about to smash the photo anyway, her date drove into the driveway. He was a couple minutes early. That made her smile.</p>
      <p style="center">+++</p>
      <p>He had prayed over the engine and God Himself jolted it to life. It's about as believable as any other way I could describe how he got that car to start. However he did it, he got there early and she came outside immediately and he got out of the car and opened her door for her, like they say a gentleman should.</p>
      <p>God, those eyes were beautiful, and they look so kind. They reminded him of his mother as she baked a cherry pie for him to eat. He wondered if she would look like Mother if she gave him cherry pie.</p>
      <p>He instantly pushed that thought out of his head. "So how have you been?"</p>
      <p>"Oh, not too bad. How has your day gone?"</p>
      <p>"Not bad at all." There was a pregnant pause. He tried to think of something to say.</p>
      <p>Anything.</p>
      <p>He couldn't.</p>
      <p>Can you blame him? It was hell trying to make out the ice on the road on the way here and so of course he was still so focused on the roads and on getting to the restaurant safely and besides there was honestly nothing interesting to say.</p>
      <p>“The roads are nice today,” she remarked about halfway to the restaurant. “They usually donʼt clear them away quite this well during winter.”</p>
      <p>He nodded and said something about good fortune and how he was worried about the roads on the way to pick her up. He thought he heard her say something else but he wasn't really listening; he was still very focused and nervous. It would be a horrible date if he lost control and careened into a ditch. He didnʼt want to make her go down in a ditch. He knew she wasnʼt that type of girl, though he didnʼt really know many girls that liked going down in ditches; it wasnʼt the sort of thing many girls liked. He needed to make sure he only did things girls would like.</p>
      <p>He tried to think about what he was going to do when he got to the restaurant. Park near to the restaurant, since it was cold. Go inside. No, go back. Open her door first, then go inside. Make sure to hold the restaurant doors too. Help her into her seat. After the waitress takes us there, of course. He hoped it was a waitress. If she was prettier then he could ignore her and focus on his date. He was worried about an attractive male waiter. He was worried she wouldnʼt ignore the waiter and then sheʼd sneak away to the bathroom and heʼd go back and find them together, in each othersʼ arms and she would look down at him with cold and cruel eyes, like he never shouldʼve been there. He hoped he was overreacting. He was sure he was overreacting. He needed to stop; he needed to think clearly.</p>
      <p>He felt a warm hand on his shoulder. “Calm down, okay?” He glanced over and saw her smiling warmly at him. She was so hot. He loved how her lips were so clean and red and vibrant. He loved her dress, how it left so much to the imagination. He loved how she wore that thick coat. So many girls would rather freeze than cover themselves up, but she didnʼt care what he thought of how she looked and that made him want her more. She patted his shoulder again and he realized he was hunched over the steering wheel like a goblin and he felt disgusted with himself. He tried to sit calmly in his seat and smile back.</p>
      <p>They arrived at the restaurant safely, of course. There was little traffic and the street lamps were all working fine and the roads were probably cleaner now than they were during some parts of summer. He had been doing too much to avoid a whole lot of nothing. Calm down, he kept telling himself. Nothing will get in your way.</p>
      <p>He helped her inside the restaurant and nearly stumbled over himself. The restaurant was completely different. The booths were new, the walls were redecorated, and there was a cookie stand where there used to be a pastry stand. He looked for anything that was the same. They had even changed the workers' uniforms.</p>
      <p>What he didn't notice right then was that they got rid of the photo that used to hang to the right of the door as you walked inside. It was a black-and-white picture of an older couple on a bridge, looking off into the distance, their faces flat like they were bored and they didnʼt want to be there having their picture taken. He used to wonder who the couple was; he always wondered if they loved each other. Now he'd never find out.</p>
      <p>The lady at the stand took them to a table; he helped his date into a chair and sat down across from her. His chair was rough and wooden and new and had sharp little round dials on the columns that dug into his spine. He hunched forward. A handsome waiter came by to get their drink order. The man started to order a drink then stopped and wondered if she wanted to order first. There was a pause and his jaw hung open uselessly for a few awkward moments. Somehow he mustered the decisiveness to point his hand at her.</p>
      <p>She took the cue and ordered a glass of water. He got a glass of water too. The waiter left and she excused herself for a moment to go to the bathroom. He felt his hand fidgeting restlessly, rubbing the edge of the tablecloth. The tablecloth stuck to his hand. He was sweating. He didnʼt know why. It wasnʼt all that hot and he had taken off his coat. He was nervous. There was no reason why he should be so nervous. She wouldnʼt run off and make out with the waiter. He remembered the kind look in her eyes; she was kind and warm and hot.</p>
      <p>He fidgeted with the tablecloth more. He wondered what she was doing in the bathroom. He pictured her standing over the sink, the water running, her face flushed. He didnʼt know if she should cry or not. He wanted her nervous because then he would feel closer to her. He saw himself going in and hugging her and everything would be okay, there was no need for her to be nervous. He was there for her.</p>
      <p>Back in reality, she was just checking her makeup in the bathroom. There was a blotch there; was it too noticeable? No, it surely isn't that noticeable. No, no, you look pretty. You look pretty. She pursed her lips and angled her head. Yes, she looked pretty.</p>
      <p>He was still rubbing his hands on the tablecloth when she came back. She looked a bit more pale to him.</p>
      <p>“This is your favorite restaurant. What do you recommend?” she asked.</p>
      <p>“Well…” He looked at his menu, which of course had been changed around. He searched for anything familiar. Nothing. “I … I like the burgers here,” he finally stammered out.</p>
      <p>It wasnʼt entirely false; he had liked the burgers, though he didnʼt know if the burgers were still good. What did he know? Everything had changed. He didnʼt know if the couple were in love, he didnʼt know if the food was still good, he didnʼt know if he deserved her. He didnʼt know if she was really pale or if he had just imagined it, and he didnʼt know if the chairs were really rough or if he was just too afraid to sit back. He didnʼt know anything. He was fumbling around like an idiot, just repeating the same mistakes over and over again. Why would anyone love you? he asked himself. Why would anyone love me? he asked himself in response. He panicked; his throat felt like it was seizing up and his vision tunneled into a dead end two feet from his face.</p>
      <p>"Excuse me, I need to go to the bathroom."</p>
      <p>"Oh, sure, of course."</p>
      <p>He stood up and bumped his leg on the table and spilled her water all over her. It splashed all over her beautiful blue dress and he saw himself in the bathroom, his hands clenched around his throat, and he didnʼt know if he was still struggling for breath or struggling to kill himself. He saw he was the one crying and she was the one coming to comfort him. He saw himself hunch over the sink and then he leapt on her like a beast as she opened her arms to embrace him. He was a monster, he would always be a monster, and no matter what he told himself he would never be able to sit up straight and see clearly.</p>
      <p><em>No. It will be alright.</em>
      </p>
      <p>He heard the voice echo in his head and he felt cool and calm, like he was back in the apartment staring out at the snow, and he had no commitments in the world.</p>
      <p>A handsome waiter came by with a cloth. He ripped it out of the waiterʼs hands, thanked him, and went down to his date.</p>
      <p>"I'm sorry," he said, wiping at her skirt.</p>
      <p>She smiled at him. "It's alright." She liked him. Why couldnʼt he calm down and see that she liked him? She smiled when he looked at her, she thanked him when he held the door and her seat, she asked him his opinion. Could she make it more obvious? She liked him; she knew he was a good person. It saddened her that he didn't realize it, though she didn't show it. She wondered if she shouldʼve worn a smaller dress, if she shouldʼve put on a shawl instead of a coat. She wanted him to look at her, but he never did. His eyes always darted away. She felt ugly and unwanted, until she finally caught his eyes, apologetic and appealing, and all was better. He liked her too. She could see it.</p>
      <p>She set down the cloth and put her hand on his shoulder. “How about we skip dinner and grab a cherry pie and get out of here?”</p>
      <p>She didnʼt want ice cream, or cake, or the “chocolate volcano”-whatever the restaurant advertised up front. She wanted a cherry pie. She was perfect.</p>
      <p>He waved the waiter over and she ordered a cherry pie to go. It came out five minutes later in a nice box with some nice disposable silverware. Ten minutes after that they were parked safely in her driveway, the engine idling.</p>
      <p>“Letʼs eat the pie right here,” she said suddenly.</p>
      <p>"Okay," he said, smiling. He got out the plastic silverware from the bag and she dug into the pie, cut several clean slices, and held one out for him on a napkin. He went to grab the cherry pie and realized that her arms were bent at exactly the same angle as his motherʼs arms when she gave him pie.</p>
      <p>She bobbed it in front of him. “What are you waiting for, whipped cream?” She grinned as he chuckled and smiled too and took the pie from her hands.</p>
      <p>“Oh, nothing. You just reminded me of my mother.” He winced as he said that. He shouldn't have said it, it was a mistake, but he looked at her and her eyes seemed so soft, and somehow even more beautiful. Her hand rustled her thin gold necklace and she nibbled her lower lip and they stared at each other for a moment longer. Then they both snapped to attention and pecked at the pie. It was good pie.</p>
      <p>She pointed at the clock. “Oh, look, itʼs 11:11. Make a wish.” She stared wistfully into the stars and he leaned in and kissed her. She kissed back and when it ended she touched her fingers to her lips and smiled bashfully. “What was that for?”</p>
      <p>“I just wanted to take a snapshot of the moment.”</p>
      <p>As he stared into the stars with her he reached over and held her hand, and as he did he remembered another lyric from the song.</p>
      <p><em>I firmly believed I didn't need anyone but me<br/>I sincerely thought I was so complete<br/>Look how wrong I can be.</em></p>
    </div>
  `
});